name: python311_psg
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - imbalanced-learn
  - missingno
  - joblib
  - opencv
  - plotly
  - ipykernel
  - jupyterlab
  - statsmodels
  - pip
  - pip:
    - tensorflow
    - ultralytics
    - transformers
    - spacy
    - selenium
    - pyautogui
    - setuptools