name: cuda_python311
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - alsa-lib=1.2.8=h166bdaf_0
  - altair=5.0.1=py311h06a4308_0
  - anyio=4.2.0=py311h06a4308_0
  - aom=3.5.0=h27087fc_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h5eee18b_0
  - arrow-cpp=11.0.0=h58bb7b3_33_cpu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py311h06a4308_0
  - attr=2.5.1=h166bdaf_1
  - aws-c-auth=0.7.3=h28f7589_1
  - aws-c-cal=0.6.1=hc309b26_1
  - aws-c-common=0.9.0=hd590300_0
  - aws-c-compression=0.2.17=h4d4d85c_2
  - aws-c-event-stream=0.3.1=h2e3709c_4
  - aws-c-http=0.7.11=h00aa349_4
  - aws-c-io=0.13.32=he9a53bd_1
  - aws-c-mqtt=0.9.3=hb447be9_1
  - aws-c-s3=0.3.14=hf3aad02_1
  - aws-c-sdkutils=0.1.12=h4d4d85c_1
  - aws-checksums=0.1.17=h4d4d85c_1
  - aws-crt-cpp=0.21.0=hb942446_5
  - aws-sdk-cpp=1.10.57=h85b1a90_19
  - babel=2.11.0=py311h06a4308_0
  - backports.cached-property=1.0.2=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.6.2=py311h06a4308_0
  - blosc=1.21.3=h6a678d5_0
  - boost-cpp=1.81.0=he95ae9e_0
  - bottleneck=1.3.7=py311hf4808d0_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py311h6a678d5_8
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cachecontrol=0.12.14=pyhd8ed1ab_0
  - cachecontrol-with-filecache=0.12.14=pyhd8ed1ab_0
  - cachetools=5.3.3=py311h06a4308_0
  - cairo=1.16.0=ha61ee94_1014
  - catalogue=2.0.10=py311h06a4308_0
  - certifi=2025.4.26=py311h06a4308_0
  - cffi=1.16.0=py311h5eee18b_1
  - cfitsio=3.470=h5893167_7
  - charls=2.2.0=h2531618_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cleo=2.1.0=pyhd8ed1ab_0
  - click=8.1.7=py311h06a4308_0
  - click-default-group=1.2.4=pyhd8ed1ab_0
  - cloudpathlib=0.16.0=py311h06a4308_1
  - cloudpickle=3.0.0=py311h06a4308_0
  - cloup=0.13.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colour=0.1.5=pyhd8ed1ab_1
  - comm=0.2.1=py311h06a4308_0
  - contourpy=1.2.0=py311hdb19cb5_0
  - cpython=3.11.12=py311hd8ed1ab_0
  - crashtest=0.4.1=pyhd8ed1ab_0
  - cryptography=42.0.2=py311hcb13ee4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - cython-blis=0.7.9=py311hf4808d0_0
  - cytoolz=0.12.2=py311h5eee18b_0
  - dask-core=2024.5.0=py311h06a4308_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distlib=0.3.8=pyhd8ed1ab_0
  - dlib=19.24.0=py311h7366164_3
  - dulwich=0.21.7=py311h459d7ec_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.2=h6a678d5_0
  - face_recognition=1.3.0=pyhd3deb0d_2
  - face_recognition_models=0.3.0=pyh9f0ad1d_0
  - ffmpeg=5.1.2=gpl_h8dda1f0_106
  - fftw=3.3.10=nompi_hf1063bd_110
  - filelock=3.15.4=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.51.0=py311h5eee18b_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h36c2ea0_0
  - fsspec=2024.3.1=py311h06a4308_0
  - future=1.0.0=pyhd8ed1ab_0
  - gettext=0.22.5=h59595ed_2
  - gettext-tools=0.22.5=h59595ed_2
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.1=h5eee18b_3
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.43=py311h06a4308_0
  - glcontext=3.0.0=py311hf86e51f_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.6.0=h6f12383_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.22.0=h4243ec0_2
  - gstreamer=1.22.0=h25f0c4b_2
  - gstreamer-orc=0.4.39=h4bc722e_0
  - harfbuzz=6.0.0=h8e241bc_0
  - hdf5=1.14.0=nompi_hb72d44e_103
  - html5lib=1.1=pyh9f0ad1d_0
  - icu=70.1=h27087fc_0
  - imagecodecs=2023.1.23=py311h8105a5c_0
  - imageio=2.33.1=py311h06a4308_0
  - imbalanced-learn=0.12.4=pyhd8ed1ab_0
  - importlib-metadata=7.0.1=py311h06a4308_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - ipykernel=6.28.0=py311h06a4308_0
  - ipython=8.25.0=py311h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.8.1=py311h06a4308_0
  - isosurfaces=0.1.0=pyhd8ed1ab_0
  - jack=1.9.22=h11f4161_0
  - jaraco.classes=3.4.0=pyhd8ed1ab_1
  - jasper=2.0.33=h0ff4b12_1
  - jedi=0.19.1=py311h06a4308_0
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jinja2=3.1.4=py311h06a4308_0
  - joblib=1.4.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py311h06a4308_0
  - jsonschema-specifications=2023.7.1=py311h06a4308_0
  - jupyter-lsp=2.2.0=py311h06a4308_0
  - jupyter_client=8.6.0=py311h06a4308_0
  - jupyter_core=5.7.2=py311h06a4308_0
  - jupyter_events=0.10.0=py311h06a4308_0
  - jupyter_server=2.14.1=py311h06a4308_0
  - jupyter_server_terminals=0.4.4=py311h06a4308_1
  - jupyterlab=4.0.11=py311h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py311h06a4308_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - jxrlib=1.1=h7b6447c_2
  - kaggle=1.6.17=pyhd8ed1ab_1
  - kagglehub=0.2.7=py311h06a4308_0
  - keyring=23.13.1=py311h38be061_0
  - kiwisolver=1.4.4=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lazy_loader=0.4=py311h06a4308_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libabseil=20230125.3=cxx17_h59595ed_0
  - libaec=1.1.3=h59595ed_0
  - libarrow=11.0.0=hb87d912_33_cpu
  - libasprintf=0.22.5=h661eb56_2
  - libasprintf-devel=0.22.5=h661eb56_2
  - libavif=0.11.1=h8182462_2
  - libblas=3.9.0=24_linux64_openblas
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libcap=2.66=ha37c62d_0
  - libcblas=3.9.0=24_linux64_openblas
  - libclang13=15.0.7=default_h5d6823c_5
  - libcrc32c=1.1.2=h6a678d5_0
  - libcups=2.3.3=h36d4200_3
  - libcurl=8.7.1=h251f7ec_0
  - libdb=6.2.32=h6a678d5_1
  - libdeflate=1.17=h5eee18b_1
  - libdrm=2.4.122=h4ab18f5_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=h28343ad_4
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgcrypt=1.11.0=h4ab18f5_1
  - libgd=2.3.3=h5aea950_4
  - libgettextpo=0.22.5=h59595ed_2
  - libgettextpo-devel=0.22.5=h59595ed_2
  - libgfortran-ng=14.1.0=h69a702a_0
  - libgfortran5=14.1.0=hc5f4f2c_0
  - libglib=2.78.4=hdc74915_0
  - libglu=9.0.0=hf484d3e_1
  - libgomp=14.2.0=h77fa898_1
  - libgoogle-cloud=2.12.0=hac9eb74_1
  - libgpg-error=1.50=h4f305b6_0
  - libgrpc=1.54.3=hb20ce57_0
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.4=h5eee18b_0
  - liblapack=3.9.0=24_linux64_openblas
  - liblapacke=3.9.0=24_linux64_openblas
  - libllvm14=14.0.6=hdb19cb5_3
  - libllvm15=15.0.7=hadd5161_1
  - libnghttp2=1.57.0=h2d74bed_0
  - libnsl=2.0.0=h5eee18b_0
  - libnuma=2.0.18=h4ab18f5_2
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libopencv=4.7.0=py311h7a0761e_1
  - libopus=1.3.1=h7b6447c_0
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=15.2=hb675445_0
  - libprotobuf=3.21.12=hfc55251_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libsystemd0=252=h2a991cd_0
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.18.1=h5e4af38_0
  - libtiff=4.5.1=h6a678d5_0
  - libtool=2.4.7=h27087fc_0
  - libudev1=253=h0b41bf4_0
  - libunistring=0.9.10=h27cfd23_0
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.18.0=h0b41bf4_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.11.0=h295c915_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.13=h1bed415_1
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.2.13=h4ab18f5_6
  - libzopfli=1.0.3=he6710b0_0
  - locket=1.0.0=py311h06a4308_0
  - lockfile=0.12.2=py_1
  - lz4-c=1.9.4=h6a678d5_1
  - manim=0.17.3=pyhd8ed1ab_0
  - mapbox_earcut=1.0.1=py311h06317a3_1
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py311h5eee18b_0
  - matplotlib-base=3.9.2=py311h6fb44e5_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - missingno=0.5.2=pyhd8ed1ab_0
  - mistune=2.0.4=py311h06a4308_0
  - mlxtend=0.23.3=pyhd8ed1ab_0
  - moderngl=5.10.0=py311h14de704_1
  - moderngl-window=2.4.1=pyhd8ed1ab_0
  - more-itertools=10.4.0=pyhd8ed1ab_0
  - mpg123=1.32.6=h59595ed_0
  - msgpack-python=1.0.8=py311h52f7536_0
  - multipledispatch=0.6.0=pyhd8ed1ab_1
  - mysql=5.7.24=h721c034_2
  - mysql-common=8.0.32=ha901b37_0
  - mysql-libs=8.0.32=hd7da12d_0
  - nbclient=0.8.0=py311h06a4308_0
  - nbconvert=7.10.0=py311h06a4308_0
  - nbformat=5.9.2=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py311h06a4308_0
  - nettle=3.9.1=h7ab15ed_0
  - networkx=2.8.8=pyhd8ed1ab_0
  - nltk=3.9.1=py311h06a4308_0
  - notebook=7.0.8=py311h06a4308_2
  - notebook-shim=0.2.3=py311h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.8.7=py311h812550d_0
  - numpy=1.26.4=py311h24aa872_0
  - numpy-base=1.26.4=py311hbfb1bba_0
  - opencv=4.7.0=py311h38be061_1
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.1.7=hb9d3cd8_0
  - orc=1.9.0=h2f23424_1
  - overrides=7.4.0=py311h06a4308_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.1=py311h06a4308_0
  - pandas=2.2.2=py311ha02d727_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.50.14=hd33c08f_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.4.1=py311h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=9.4.0=py311h6a678d5_1
  - pixman=0.40.0=h7f8727e_1
  - pkginfo=1.11.1=pyhd8ed1ab_0
  - platformdirs=3.10.0=py311h06a4308_0
  - ply=3.11=py311h06a4308_0
  - poetry=1.5.1=linux_pyhd8ed1ab_0
  - poetry-core=1.6.1=pyhd8ed1ab_0
  - poetry-plugin-export=1.5.0=pyhd8ed1ab_0
  - polars=1.30.0=default_h1443d73_0
  - polars-default=1.30.0=py39hfac2b71_0
  - prometheus_client=0.14.1=py311h06a4308_0
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pulseaudio=16.1=ha8d29e2_1
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-opencv=4.7.0=py311h781c19f_1
  - pyarrow=11.0.0=py311hd8e8d9b_1
  - pybind11-abi=4=hd3eb1b0_1
  - pycairo=1.25.0=py311h8feb60e_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic-core=2.20.1=py311hb02cf49_0
  - pydeck=0.8.0=py311h06a4308_2
  - pydub=0.25.1=pyhd8ed1ab_0
  - pyglet=1.5.27=py311h38be061_4
  - pygments=2.15.1=py311h06a4308_1
  - pyparsing=3.0.9=py311h06a4308_0
  - pyproject_hooks=1.1.0=pyhd8ed1ab_0
  - pyqt=5.15.10=py311h6a678d5_0
  - pyqt5-sip=12.13.0=py311h5eee18b_0
  - pyrr=0.10.3=py_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.0=he550d4f_1_cpython
  - python-build=0.10.0=pyhd8ed1ab_1
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-fastjsonschema=2.16.2=py311h06a4308_0
  - python-gil=3.11.12=hd8ed1ab_0
  - python-installer=0.7.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=py311h06a4308_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.11=4_cp311
  - pytz=2024.1=py311h06a4308_0
  - pywavelets=1.5.0=py311hf4808d0_0
  - pyyaml=6.0.1=py311h5eee18b_0
  - pyzmq=25.1.2=py311h6a678d5_0
  - qhull=2020.2=hdb19cb5_2
  - qt-main=5.15.8=h5d23da1_6
  - qtconsole=5.5.1=py311h06a4308_0
  - qtpy=2.4.1=py311h06a4308_0
  - rapidfuzz=3.9.6=py311hf86e51f_0
  - rdma-core=28.9=h59595ed_1
  - re2=2023.03.02=h8c504da_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py311h06a4308_0
  - regex=2024.9.11=py311h5eee18b_0
  - requests=2.32.3=py311h06a4308_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=py311h06a4308_0
  - rfc3986-validator=0.1.1=py311h06a4308_0
  - rich=13.7.1=pyhd8ed1ab_0
  - rpds-py=0.10.6=py311hb02cf49_0
  - s2n=1.3.49=h06160fa_0
  - scikit-image=0.24.0=py311ha02d727_0
  - scikit-learn=1.5.1=py311ha02d727_0
  - scipy=1.13.1=py311h24aa872_0
  - screeninfo=0.8.1=py311h38be061_2
  - seaborn=0.13.2=py311h06a4308_0
  - secretstorage=3.3.3=py311h38be061_2
  - send2trash=1.8.2=py311h06a4308_0
  - setuptools=72.1.0=py311h06a4308_0
  - shellingham=1.5.4=pyhd8ed1ab_0
  - sip=6.7.12=py311h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - skia-pathops=0.7.4=py311h4dd048b_0
  - smart_open=5.2.1=py311h06a4308_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.1.10=h6a678d5_1
  - sniffio=1.3.0=py311h06a4308_0
  - soupsieve=2.5=py311h06a4308_0
  - spacy-legacy=3.0.12=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - srsly=2.4.8=py311h6a678d5_1
  - srt=3.5.3=py311h38be061_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - streamlit=1.40.2=pyhd8ed1ab_0
  - svgelements=1.9.6=pyhd8ed1ab_0
  - svt-av1=1.4.1=hcb278e6_0
  - tenacity=9.0.0=py311h06a4308_0
  - terminado=0.17.1=py311h06a4308_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - threadpoolctl=3.5.0=py311h92b7b1e_0
  - tifffile=2023.4.12=py311h06a4308_0
  - tinycss2=1.2.1=py311h06a4308_0
  - tk=8.6.14=h39e8969_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.13.2=pyha770c72_0
  - toolz=0.12.0=py311h06a4308_0
  - tornado=6.4.1=py311h5eee18b_0
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=py311h06a4308_0
  - trove-classifiers=2024.7.2=pyhd8ed1ab_0
  - typing=3.10.0.0=pyhd8ed1ab_1
  - typing_extensions=4.11.0=py311h06a4308_0
  - tzlocal=5.2=py311h06a4308_0
  - ucx=1.14.1=h64cca9d_5
  - unicodedata2=15.1.0=py311h5eee18b_0
  - unidecode=1.3.8=py311h06a4308_0
  - validators=0.18.2=pyhd3eb1b0_0
  - virtualenv=20.26.3=pyhd8ed1ab_0
  - watchdog=2.3.1=py311h38be061_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311h06a4308_1
  - websocket-client=1.8.0=py311h06a4308_0
  - wheel=0.43.0=py311h06a4308_0
  - widgetsnbextension=3.6.6=py311h06a4308_0
  - wordcloud=1.9.4=py311h9ecbd09_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zfp=1.0.0=h6a678d5_0
  - zipp=3.17.0=py311h06a4308_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.5=hc292b87_2
  - pip:
      - absl-py==2.1.0
      - annotated-types==0.7.0
      - argparse==1.4.0
      - arrow==1.3.0
      - astroid==3.3.4
      - astunparse==1.6.3
      - attrs==24.2.0
      - blis==1.0.1
      - chardet==3.0.4
      - clipboard==0.0.4
      - cohere==5.13.3
      - confection==0.1.5
      - cymem==2.0.10
      - deep-translator==1.11.4
      - dill==0.3.8
      - distro==1.9.0
      - edflib-python==1.0.8
      - es-core-news-sm==3.7.0
      - fastavro==1.9.7
      - flatbuffers==24.3.25
      - fqdn==1.5.1
      - gast==0.6.0
      - google-auth==2.36.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.1
      - google-pasta==0.2.0
      - googletrans==3.0.0
      - grpcio==1.67.0
      - gspread==6.1.4
      - h11==0.9.0
      - h2==3.2.0
      - h5py==3.12.1
      - hpack==3.0.0
      - hstspreload==2024.12.1
      - httpcore==0.9.1
      - httplib2==0.22.0
      - httpx==0.13.3
      - httpx-sse==0.4.0
      - huggingface-hub==0.26.3
      - hyperframe==5.2.0
      - idna==2.10
      - iso8601==2.1.0
      - isoduration==20.11.0
      - isort==5.13.2
      - jiter==0.8.0
      - jsonpointer==3.0.0
      - keras==3.6.0
      - langcodes==3.5.0
      - language-data==1.3.0
      - libclang==18.1.1
      - manimpango==0.5.0
      - marisa-trie==1.2.1
      - markdown==3.7
      - mccabe==0.7.0
      - ml-dtypes==0.4.1
      - mne==1.9.0
      - mouseinfo==0.1.3
      - mpmath==1.3.0
      - murmurhash==1.0.11
      - namex==0.0.8
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - oauthlib==3.2.2
      - openai==1.57.0
      - opt-einsum==3.4.0
      - optree==0.13.0
      - outcome==1.3.0.post0
      - paho-mqtt==2.1.0
      - parameterized==0.9.0
      - pip==25.1.1
      - plotly==5.23.0
      - pooch==1.8.2
      - preshed==3.0.9
      - protobuf==4.25.5
      - py-cpuinfo==9.0.0
      - py2flowchart==0.0.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pyautogui==0.9.54
      - pydantic==2.10.2
      - pyedflib==0.1.38
      - pyflowchart==0.3.1
      - pygetwindow==0.0.9
      - pylint==3.3.1
      - pymodbus==3.7.4
      - pymsgbox==1.0.9
      - pymupdf==1.25.5
      - pypdf==5.4.0
      - pyperclip==1.9.0
      - pyrect==0.2.0
      - pyscreeze==1.0.1
      - pyserial==3.5
      - python-graphviz==0.20.3
      - python3-xlib==0.15
      - pytweening==1.2.0
      - requests-oauthlib==2.0.0
      - rfc3986==1.5.0
      - rsa==4.9
      - safetensors==0.4.5
      - selenium==4.26.1
      - serial==0.0.97
      - smart-open==7.0.5
      - sortedcontainers==2.4.0
      - spacy==3.7.5
      - spacy-loggers==1.0.5
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.17.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - thinc==8.3.2
      - tokenizers==0.20.3
      - torch==2.7.0
      - torchvision==0.22.0
      - transformers==4.46.3
      - trio==0.27.0
      - trio-websocket==0.11.1
      - triton==3.3.0
      - typer==0.9.4
      - types-python-dateutil==2.9.0.20241206
      - types-requests==2.32.0.20241016
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - ultralytics==8.3.121
      - ultralytics-thop==2.0.14
      - uri-template==1.3.0
      - urllib3==2.2.3
      - wasabi==1.1.3
      - weasel==0.4.1
      - webcolors==24.11.1
      - werkzeug==3.0.4
      - wrapt==1.16.0
      - wsproto==1.2.0
prefix: /home/asper/anaconda3/envs/cuda_python311
